open ai functionality addition
kalviumcommunity/compilerd pull request #13
Opened 2023-12-26 12:32 UTC by anipnwr7777

Intergrated OPEN_AI to evaluate subjective answers against a prompt and return a score and a rationale.

2023-12-26 13:04 UTC, yash0212 requested changes
Please resolve the added comments

2023-12-26 13:04 UTC, yash0212 commented on services/code.service.js
> +        if (req.language === 'promptv1') {
Please remove the redundant conditions

2023-12-26 13:04 UTC, yash0212 commented on services/code.service.js
> +            await executePrompt(req, res, response);
Please update the function to accept parameters directly. Example
```
const _resp = await executePrompt(LANGUAGES_CONFIG[req.language], prompt);
response.errorMessage = _res.errorMessage ?? response.errorMessage
```

2023-12-26 13:04 UTC, yash0212 commented on services/code.service.js
> +const executePrompt = async (req, res, response) => {
Please rename the function to `_executePrompt` as it is an internal function and update the function parameters to  `async (langConfig, prompt)`

2023-12-26 13:04 UTC, yash0212 commented on services/code.service.js
> +        try {
Please check if this try catch can be moved on top of the `if-else` block so that it handles errors in all conditions

2023-12-26 16:37 UTC, anipnwr7777 commented on services/code.service.js
> +const executePrompt = async (req, res, response) => {
done

2023-12-26 16:37 UTC, anipnwr7777 commented on services/code.service.js
> +        if (req.language === 'promptv1') {
sorry for the typo, removed it.

2023-12-27 13:03 UTC, yash0212 approved these changes
LGTM

2024-01-02 08:58 UTC, closed without merging