Add sqlite support
kalviumcommunity/compilerd pull request #48
Opened 2024-06-04 11:09 UTC by shashanksingh2002

- Add support for sqlite3 language

2024-06-07 12:29 UTC, anipnwr7777 requested changes

2024-06-07 12:29 UTC, anipnwr7777 commented on services/code.service.js
> +    const dbPath = '/tmp/database.db'
Please move this to a config

2024-06-07 12:29 UTC, anipnwr7777 commented on services/code.service.js
> +    const cleanedQueries = []
See if this could be renamed to something like `formattedQueries` or something more relevant.

2024-06-07 12:29 UTC, anipnwr7777 commented on services/code.service.js
> +                'Was not able to connect to the SQLite database: ' + err.message,
Please make sure that err.message is not an object in any case if we want to concatenate it to a string otherwise details will be lost.

2024-06-07 12:29 UTC, anipnwr7777 commented on services/code.service.js
> +    } catch (err) {
I don't see a cleanup of the file `/tmp/database.db` once the request is served, please check if that is needed.

2024-06-10 06:29 UTC, kailashchoudhary11 commented on services/code.service.js
> +    const dbPath = '/tmp/database.db'
Fixed in  1034cd6

2024-06-10 10:59 UTC, anipnwr7777 approved these changes
LGTM

2024-06-10 13:01 UTC, merged